language: python
python:
- '2.7'
- pypy
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
env:
  global:
  - secure: gYiqOw7SRuM7uvVWKuD6/qmBuN4aUVVNEFrYBjA08G9TFgPAr2sRfXOYNljSwQf2AVLZ9kDvuWQgvqaeFGjucll9js6Fa5QaeZTAYVQX4v3fXOQ/NbtFt2CCi1kRV8rWCDoINnUe+SJp9zudVda2xYvYqyYxJkH0zWAk+Yk4FPo=
  - secure: kNPFXpGOJbMMmBAHV8AbpI9nvxAi7OcvRWs0b90Jf/Y/gdtVowe6/EgfTmQ1uxbSd5U4AZb3D4eABxfYo1ywbmYBeC0ATEV2+I/3GiZUpSbbxedJkunXTPEYDcOruWcgO1wrdNshrW7CnFCf0MBnC4M0fzMfIxyuAYCHExca3pA=
  jobs:
  - HTTPLIB=requests pytz
  - HTTPLIB=pytz
  - HTTPLIB=requests
  - HTTPLIB=
stages:
- test
- lint
jobs:
  include:
  - python: '3.8'
    install: pip install flake8
    script: flake8
    stage: lint
install:
- pip install pytest
- if ! [ -z "$HTTPLIB" ]; then pip install $HTTPLIB; fi
script: pytest tests.py
notifications:
  slack:
    rooms:
      secure: ZMIVcIxsNKY8slDiOzNArVjqnmkq5kEwU0VXUej6cSSO+vC7ZAv9zEpTA3AOTybkOD7tARaHgmjPDb5R/ERq1zGabvAVAYLNo4p0OZSkQVRr7wniGkuwjOKfKienPeuXhXuLvdJaVK7eT82gq7rXQO8TK+rpKtUfwCCy4YwW+QU=
