language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
env:
  - HTTPLIB=requests pytz
  - HTTPLIB=pytz
  - HTTPLIB=requests
  - HTTPLIB=
install:
  - pip install $HTTPLIB
script: nosetests
notifications:
  slack: ivelum:m5sGlwz1uEy5sQ32n0kg9lNh
