language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - HTTPLIB=requests pytz
  - HTTPLIB=pytz
  - HTTPLIB=requests
  - HTTPLIB=
install:
  - pip install pytest
  - if ! [ -z "$HTTPLIB" ]; then pip install $HTTPLIB; fi
script: pytest tests.py
notifications:
  slack:
    rooms:
      secure: ZMIVcIxsNKY8slDiOzNArVjqnmkq5kEwU0VXUej6cSSO+vC7ZAv9zEpTA3AOTybkOD7tARaHgmjPDb5R/ERq1zGabvAVAYLNo4p0OZSkQVRr7wniGkuwjOKfKienPeuXhXuLvdJaVK7eT82gq7rXQO8TK+rpKtUfwCCy4YwW+QU=
